"""Shared command-line defaults for Stratachrome tools."""

DEFAULT_SIZE_MM = 200.0
DEFAULT_MAX_DIM = 1000
DEFAULT_FIRST_LAYER_HEIGHT_MM = 0.20
DEFAULT_LAYER_HEIGHT_MM = 0.10
DEFAULT_COLORS_PER_TIER = 4
DEFAULT_MAX_LAYERS_PER_TIER = 20
DEFAULT_TOTAL_LAYERS = 27
